name: statgo CI

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: [ '1.21.x' ]

    steps:
      - uses: actions/checkout@v4
      - name: Setup Go ${{ matrix.go-version }}
        uses: actions/setup-go@v4
        with:
          go-version: ${{ matrix.go-version }}
      - name: Install libstatgrab-dev
        run: sudo apt-get install -y libstatgrab-dev
      - name: Install dependencies
        run: |
          go get .
      - name: Display Go version
        run: go version
      - name: Run tests
        run: go test